name: Bug report
description: Create a report to help us improve
title: "Bug title"
labels: [bug]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    validations:
      required: true
    attributes:
      label: App version
      description: Specify the version of Coolapk Lite you're using.
      options:
        - "0.0.3"
        - "0.0.2"
        - "0.0.1"
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      options:
        - "Insider Build (xxxxx)"
        - "Windows 11 version 24H2 (26100, 2024 Update)"
        - "Windows 11 version 23H2 (22631, November 2023 Update)"
        - "Windows 11 version 22H2 (22621, 2022 Update)"
        - "Windows 11 version 21H2 (22000)"
        - "Windows 10 version 22H2 (19045, 2022 Update)"
        - "Windows 10 version 21H2 (19044, November 2021 Update)"
        - "Windows 10 version 21H1 (19043, May 2021 Update)"
        - "Windows 10 version 20H2 (19042, October 2020 Update)"
        - "Windows 10 version 2004 (19041, May 2020 Update)"
        - "Windows 10 version 1909 (18363, November 2019 Update)"
        - "Windows 10 version 1903 (18362, May 2019 Update)"
        - "Windows 10 version 1809 (17763, October 2018 Update)"
        - "Windows 10 version 1803 (17134, April 2018 Update)"
        - "Windows 10 version 1709 (16299, Fall Creators Update)"
        - "Windows 10 version 1709 (15254, Fall Creators Update)"
        - "Windows 10 version 1703 (15063, Creators Update)"
        - "Windows 10 version 1607 (14393, Anniversary Update)"
        - "Windows 10 version 1511 (10586, November Update)"
        - "Windows 10 version 1507 (10240)"
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Device
      description: Which Devices did you see the issue on?
      options:
        - "Desktop"
        - "Mobile"
        - "Xbox"
        - "Hololens"
        - "Hub"
        - "IOT"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
